config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'health/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :users, only: [:index, :show] do
    resources :posts do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create, :destroy]
    end
  end

  root 'users#index'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index] do
        resources :posts, only: [:index] do
          resources :comments, only:[:index, :create]
        end
      end
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    user ||= User.new # Guest user (not logged in)

    if user.admin?
      can :manage, :all # Admin can manage all resources
    else
      # Users can read and create their own posts and comments
      can %i[read create], [Post, Comment]
      # Users can update and destroy their own posts and comments
      can %i[update destroy], [Post, Comment], author_id: user.id
    end
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :increase_comment_counter

  def increase_comment_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_likes_counter

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes

  after_save :update_author_posts_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def update_author_posts_counter
    author.increment!(:posts_counter)
  end

  def top_five_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def admin?
    role == 'admin'
  end

  def top_three_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  before_action :find_post

  def index
    # http://127.0.0.1:3000/api/v1/users/1/posts/102/comments
    @comments = @post.comments
    render json: @comments
  end

  # POST http://127.0.0.1:3000/api/v1/users/1/posts/102/comments
  def create
    @user_id = params[:comment][:author_id]
    @comment = @post.comments.build(text: comment_params[:text], author_id: @user_id)

    if @comment.save
      render json: @comment, status: :created
    else
      render json: { errors: @comment.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def find_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:text, :author_id)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  before_action :find_user

  # http://127.0.0.1:3000/api/v1/users/1/posts

  def index
    @posts = @user.posts
    render json: @posts
  end

  private

  def find_user
    @user = User.includes(posts: :comments).find(params[:user_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @user = current_user
    @post = Post.find(params[:post_id])

    @new_comment = @post.comments.build(text: comment_params[:text], author_id: @user.id)
    respond_to do |format|
      format.html do
        if @new_comment.save
          redirect_to user_post_path(current_user, @post), notice: 'Comment created successfully'
        else
          redirect_to user_post_path(current_user, @post), alert: 'Cannot create comment'
        end
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    authorize! :destroy, @comment
    @comment.destroy
    redirect_to user_post_path(@comment.post), notice: 'Comment was successfully deleted.'
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/health_controller.rb
class HealthController < ApplicationController
  def index
    render json: { status: 'online' }, status: 200
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post

  def create
    @like = @post.likes.build(author_id: current_user.id)
    if @like.save
      redirect_to user_post_path(current_user, @post), notice: 'Post liked'
    else
      redirect_to user_post_path(current_user, @post), notice: 'Post Cannot be liked'
    end
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_user

  def index
    @user_posts = @user.posts.includes(:comments)
  end

  def new
    @post = Post.new
  end

  def create
    @post = @user.posts.build(post_params)
    if @post.save
      redirect_to user_post_path(@user, @post), notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def show
    @user = User.includes(posts: :comments).find(params[:user_id])
    @user_post = @user.posts.includes(:comments).find_by(id: params[:id])
    @like = Like.new
  end

  def destroy
    @user = User.includes(posts: :comments).find(params[:user_id])
    @user_post = @user.posts.includes(:comments).find_by(id: params[:id])
    @user_post.destroy
    redirect_to user_posts_path(@user), status: :see_other
  end

  private

  def find_user
    @user = User.includes(posts: :comments).find(params[:user_id])
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/api/posts_helper.rb
module Api::PostsHelper
end

app/helpers/api/v1/comments_helper.rb
module Api::V1::CommentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/health_helper.rb
module HealthHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/comments/new.html.erb
<h1> Create a comment on behalf of current user </h1>

<%=form_with model: @comment, url: user_post_comments_path(user_id: @user, post_id: @post) do |form| %>
  <div>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </div>

  <div>
    <%= form.submit "Create Comment for this Post" %>
  </div>

<% end %>

app/views/health/index.html.erb
<h1>Health#index</h1>
<p>Find me in app/views/health/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TubongeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <div class="container">
   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
  </body>
</html>

app/views/partials/_like_button.html.erb
<%= form_with model: [user, post, like], url: user_post_likes_path(user, post), class: "form", scope: :like do |f| %>
  <%= f.submit "Like", class: "submit_button" %>
<% end %>


app/views/partials/_post.html.erb
<div class="post">
        <h3><%= link_to post.title, user_post_path(user_id: @user.id, id: post.id) %></h3>
        <p><%= post.text %></p>
        <p class="stats"> Comments: <%= post.comments_counter%> Likes: <%=post.likes_counter%> </p>
        

    </div>

app/views/partials/_user.html.erb
<div class="user-wrapper">
    <img src="<%=user.photo%>" />
    <div class="content">
    <a href="<%= user_path(user) %>" class="user-link"><%= user.name %></a>
      <p>Number of posts: <%=user.posts_counter%></p>
    </div>
</div>

app/views/posts/index.html.erb
  <%= render partial: 'partials/user', locals: {user: @user} %>
   <% @user.posts.each do |post| %>
     <%= render partial: 'partials/post', locals: { post: post } %>
     <div class="all-comments">
    <% post.top_five_comments.each do |comment| %>
      <p><%=link_to comment.author, user_path(comment.author)%> :  <%=comment.text%></p>
    <% end %>
     </div>
   <% end %>
   <button>Pagination</button>


app/views/posts/new.html.erb
<h1> Create a New Post for current_user" </h1>

<%= form_with model: [@user, @post], url: user_posts_path(@user) do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </div>

  <div>
    <%= form.submit "Create Post" %>
  </div>

<% end %>


app/views/posts/show.html.erb
<div class="upper">
  <div class="p-content">
    <p><%= @user_post.title %> by <%= link_to @user.name, user_path(@user) %></p>
    <p>Comments: <%= @user_post.comments_counter %> Likes: <%= @user_post.likes_counter %></p>
  </div>
  <p><%= @user_post.text %></p>
  <p><%= render partial: 'partials/like_button', locals: { user: @user, post: @user_post, like: @like } %></p>
  <% if can? :destroy, @user_post %>
    <%= link_to 'Delete', user_post_path(@user, @user_post), data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this post?' }%>
  <% end %>
</div>

<div class="comments-section">
  <% @user_post.comments.each do |comment| %>
    <p><%= link_to comment.author, user_path(comment.author) %>: <%= comment.text %></p>
    <% if can? :destroy, comment %>
        <%= link_to 'Delete', user_post_comment_path(@user, @user_post, comment), data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this comment?' }%>
      <% end %>
  <% end %>
</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= render partial: 'partials/user', locals: { user: user } %>
<%end %>

app/views/users/show.html.erb

  <%= render partial: 'partials/user', locals: { user: @user } %>
  <div class="bio">
    <h3>Bio</h3>
    <p><%=@user.bio%></p>
  </div>
  <div class="posts">
    <% @user.top_three_posts.each do |post| %>
      <%= render partial: 'partials/post', locals: { post: post} %>
    <% end %>
  </div>
  <%= link_to "See All Posts", user_posts_path(@user), class: "btn" %>
</div>